services:
  fastlane:
    environment:
      CONTENT_DATA_DIR: '/app/data'
      UPLOADS_DIR: '/app/uploads'
    ports:
      - '3000:3000'
    volumes:
      - ./data:/app/data
      - ./data/uploads:/app/uploads
