services:
  fastlane:
    build:
      context: /datastore/fastlane/app
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: 'production'
      HOST: '0.0.0.0'
      PORT: '3000'
      PUBLIC_BASE_URL: 'https://fastlane.octotech.az'
      OLLAMA_CHAT_URL: 'http://host.docker.internal:11434/api/chat'
      OLLAMA_MODEL: 'humane:6.1'
    ports:
      - '3000:3000'
    volumes:
      - /datastore/fastlane/uploads:/app/data/uploads
      - /datastore/fastlane/data:/app/data
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - edge
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=edge'
      - 'traefik.http.routers.fastlane.rule=Host(`fastlane.octotech.az`)'
      - 'traefik.http.routers.fastlane.entrypoints=web'
      - 'traefik.http.services.fastlane.loadbalancer.server.port=3000'
      - 'traefik.http.routers.fastlane-api.rule=(Host(`fastlane.octotech.az`)) && (PathPrefix(`/api`) || PathPrefix(`/uploads`))'
      - 'traefik.http.routers.fastlane-api.entrypoints=web'
      - 'traefik.http.routers.fastlane-api.priority=100'
      - 'traefik.http.services.fastlane-api.loadbalancer.server.port=3000'

networks:
  edge:
    external: true
